import Head from "next/head";
import Link from "next/link";
import Nav from "@/components/Nav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Insight Pest Solutions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sticky top-0 flex h-16 items-center justify-between bg-green-800 px-4 sm:px-6 lg:px-8">
        <div className="flex items-center">
          <img
            src="https://insightpestcanada.com/wp-content/uploads/2023/04/insight-canada-logo.png"
            alt="Logo"
            className="h-8 w-auto"
          />
        </div>
        <div className="flex w-full max-w-[250px] justify-between md:max-w-[350px]">
          <a
            className="font-bold text-white hover:text-green-200"
            href="https://insightpestcanada.com/about/"
          >
            À propos
          </a>
          <a
            className="font-bold text-white hover:text-green-200"
            href="https://insightpestcanada.com/locations/"
          >
            Emplacements
          </a>
          <a
            className="hover:text-green-2 font-bold text-white"
            href="https://insightpestcanada.com/services-insight-pest-solutions/rodent-control/"
          >
            Services
          </a>
        </div>
        <div></div>
      </div>
      <main className="flex min-h-[100dvh] w-full flex-col items-center justify-between bg-gradient-to-r from-green-700 to-white md:flex-row">
        <div className="flex-1 p-8 text-center md:p-12 md:text-left lg:p-16">
          <h1 className="mb-4 text-4xl font-bold text-white md:text-5xl lg:text-6xl">
            Éliminez les rongeurs pour de bon.
          </h1>
          <p className="mb-8 text-lg text-white md:text-xl lg:text-2xl">
            Notre équipe d'experts en lutte contre les nuisibles débarrassera
            rapidement et efficacement votre maison des souris, des rats et
            d'autres rongeurs.
          </p>
          <form className="mx-auto max-w-md rounded-lg bg-white p-6 shadow-lg md:mx-0 md:p-8 lg:p-10">
            <div className="mb-4">
              <label
                htmlFor="name"
                className="mb-2 block text-sm font-medium text-green-500"
              >
                Nom complet
              </label>
              <input
                className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                id="name"
                type="text"
                placeholder="Enter votre nom complet"
              />
            </div>
            <div className="mb-6">
              <label
                htmlFor="phone"
                className="mb-2 block text-sm font-medium text-green-500"
              >
                Numéro de téléphone
              </label>
              <input
                id="phone"
                type="tel"
                placeholder="Entrez votre numéro de téléphone"
                className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              />
            </div>
            <button
              type="submit"
              className="ring-offset-background focus-visible:ring-ring hover:bg-primary/90 inline-flex h-10 w-full items-center justify-center whitespace-nowrap rounded-md bg-black px-4 py-2 text-sm font-medium text-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
            >
              Consulter gratuitement ➜
            </button>
          </form>
        </div>
        <div className="mt-10 flex-1 md:block">
          <img
            src="https://insightpestcanada.com/wp-content/uploads/2024/07/DSC05667.jpg"
            alt="Rodent Pest Control"
            width={600}
            height={600}
            className="h-full w-full rounded-full object-cover"
            style={{ aspectRatio: "600/600", objectFit: "cover" }}
          />
        </div>
      </main>
    </>
  );
}
