import Head from "next/head";

import axios from "axios";

export default function Home() {
  const submitForm = async (e: FormDataEvent) => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    console.log({ formData });
    const name = formData.get("name");
    const phone = formData.get("phone");

    if (!name || !phone) {
      alert("Please fill in all fields");
      return;
    }

    await axios.post("/api/lead", { name, phone }).then((res) => {
      console.log(res);
      alert("Thank you for your submission!");
    });
  };

  return (
    <>
      <Head>
        <title>Insight Pest Solutions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sticky top-0 flex h-16 items-center justify-between bg-black px-4 sm:px-6 lg:px-8">
        <div className="flex items-center">
          <img
            src="https://insightpestcanada.com/wp-content/uploads/2023/04/insight-canada-logo.png"
            alt="Logo"
            className="h-8 w-auto"
          />
        </div>
        <div className="flex w-full max-w-[250px] justify-center md:max-w-[350px] md:justify-between">
          <a
            className="hidden font-bold text-white hover:text-green-200 md:block"
            href="https://insightpestcanada.com/about/"
          >
            À propos
          </a>
          <a
            className="hidden font-bold text-white hover:text-green-200 md:block"
            href="https://insightpestcanada.com/locations/"
          >
            Emplacements
          </a>
          <a
            className="hover:text-green-2 hidden font-bold text-white md:block"
            href="https://insightpestcanada.com/services-insight-pest-solutions/rodent-control/"
          >
            Services
          </a>
        </div>
        <div></div>
      </div>
      <main className="flex min-h-[100dvh] w-full flex-col items-center justify-between bg-gradient-to-r from-green-600 to-green-200 md:flex-row">
        <div className="mt-10 flex-1 md:block">
          <img
            src="https://insightpestcanada.com/wp-content/uploads/2024/07/DSC05667.jpg"
            alt="Rodent Pest Control"
            width={400}
            height={400}
            className="ml-4 h-full w-full rounded-full object-cover"
            style={{ aspectRatio: "600/600", objectFit: "cover" }}
          />
        </div>
        <div className="mx-12 flex-1 p-8 text-center md:p-12 md:text-left lg:p-16">
          <h1 className="mb-4 text-4xl font-bold text-white md:text-5xl lg:text-6xl">
            Finit les souris!
          </h1>
          <p className="mb-4 text-xl text-white">
            Éliminer les rongeurs pour de bon.
          </p>
          <div>
            <form
              className="mx-auto max-w-md rounded-lg bg-white p-6 shadow-lg md:mx-0 md:p-8 lg:p-10"
              onSubmit={(e) => submitForm(e as unknown as FormDataEvent)}
            >
              <h2 className="mb-4 text-center text-2xl font-bold text-green-500">
                Demandez une estimation gratuite
              </h2>
              <div className="mb-4">
                <label
                  htmlFor="name"
                  className="mb-2 block text-sm font-medium text-green-500"
                >
                  Nom complet
                </label>
                <input
                  className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  id="name"
                  name="name"
                  type="text"
                  placeholder="Gylaine Tremblay"
                />
              </div>
              <div className="mb-6">
                <label
                  htmlFor="phone"
                  className="mb-2 block text-sm font-medium text-green-500"
                >
                  Numéro de téléphone
                </label>
                <input
                  name="phone"
                  id="phone"
                  type="tel"
                  placeholder="(555) 555-5555"
                  className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full rounded-md border px-3 py-2 text-sm file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                />
              </div>
              <button
                type="submit"
                className="ring-offset-background focus-visible:ring-ring hover:bg-primary/90 inline-flex h-10 w-full animate-bounce items-center justify-center whitespace-nowrap rounded-md bg-black px-4 py-2 text-sm font-medium text-white transition-all hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
              >
                Estimation Gratuite ➜
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
